ScoreException: Remove irrelevant constructor comment
This comment doesn't add anything to the constructor method and
of course looking at the constructor, one will definitely know it
is a constructor. So the added constructor comment at the top adds
no useful information.

Change-Id: Ibfb0dd2f696b27ea067bb785452345d872ac8188